sonar.projectKey=slima4_lumen-argus
sonar.organization=slima4
sonar.python.version=3.9,3.10,3.11,3.12,3.13
sonar.sources=lumen_argus
sonar.tests=tests
sonar.exclusions=docs/**,landing.html,benchmark.py
