sonar.projectKey=lumen-argus_lumen-argus
sonar.organization=lumen-argus
sonar.python.version=3.11
sonar.sources=packages/core/lumen_argus_core,packages/agent/lumen_argus_agent,packages/proxy/lumen_argus
sonar.tests=tests,packages/core/tests,packages/agent/tests
sonar.exclusions=docs/**,landing.html,benchmark.py
