"""CA certificate management for forward proxy TLS interception.

Generates and manages a local Certificate Authority used by the forward
proxy (mitmproxy) to intercept HTTPS traffic from AI tools that don't
support custom base URLs.

Certificate files:
    ~/.lumen-argus/ca/ca-cert.pem   — CA certificate (public, shared with tools)
    ~/.lumen-argus/ca/ca-key.pem    — CA private key (0o600, never transmitted)

The CA is generated once on first forward proxy start and reused across
restarts.  Expiry is 10 years — no rotation needed for v1.
"""

from __future__ import annotations

import logging
import os
import platform
import subprocess

log = logging.getLogger("argus.forward.ca")

_ARGUS_DIR = os.path.expanduser("~/.lumen-argus")
_CA_DIR = os.path.join(_ARGUS_DIR, "ca")
_CA_CERT_PATH = os.path.join(_CA_DIR, "ca-cert.pem")
_CA_KEY_PATH = os.path.join(_CA_DIR, "ca-key.pem")

# mitmproxy default CA location (used as fallback)
_MITMPROXY_CA_DIR = os.path.expanduser("~/.mitmproxy")
_MITMPROXY_CA_CERT = os.path.join(_MITMPROXY_CA_DIR, "mitmproxy-ca-cert.pem")

# CA Common Name — used by _is_trusted_macos() to look up the cert in the
# System keychain. Must stay in sync with whatever CN mitmproxy stamps
# onto the CA it generates inside ``_CA_DIR``.
_CA_CN = "lumen-argus Forward Proxy CA"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def get_ca_cert_path() -> str:
    """Return path to the CA certificate PEM file.

    Returns our custom CA path if it exists, otherwise falls back to
    mitmproxy's default CA (generated by mitmproxy on first run).
    """
    if os.path.isfile(_CA_CERT_PATH):
        return _CA_CERT_PATH
    if os.path.isfile(_MITMPROXY_CA_CERT):
        return _MITMPROXY_CA_CERT
    return _CA_CERT_PATH  # Expected path (not yet generated)


def get_ca_key_path() -> str:
    """Return path to the CA private key PEM file."""
    return _CA_KEY_PATH


def get_ca_dir() -> str:
    """Return the CA directory path."""
    return _CA_DIR


def ca_exists() -> bool:
    """Check if CA cert exists (public cert for trust + combined PEM for mitmproxy)."""
    combined = os.path.join(_CA_DIR, "mitmproxy-ca.pem")
    return os.path.isfile(_CA_CERT_PATH) and os.path.isfile(combined)


def ensure_ca() -> str:
    """Ensure CA certificate exists, generating if needed.

    On first run, starts a temporary mitmproxy instance to generate the CA
    in our confdir, then extracts the public cert for users to trust.
    This ensures mitmproxy always uses its own generated CA (compatibility
    guaranteed) while we control the storage location.

    Returns path to the CA certificate PEM file.
    """
    if ca_exists():
        log.debug("CA certificate exists: %s", _CA_CERT_PATH)
        return _CA_CERT_PATH

    log.info("generating CA certificate for forward proxy TLS interception")

    # Create confdir so mitmproxy generates CA into our directory
    os.makedirs(_CA_DIR, mode=0o700, exist_ok=True)

    # Let mitmproxy generate the CA by briefly initializing options with our confdir.
    # mitmproxy auto-generates mitmproxy-ca.pem (combined key+cert) and
    # mitmproxy-ca-cert.pem (public cert only) into confdir on first access.
    from mitmproxy import certs as mitm_certs

    ca_combined = os.path.join(_CA_DIR, "mitmproxy-ca.pem")
    if not os.path.isfile(ca_combined):
        # Trigger CA generation via mitmproxy's CertStore
        mitm_certs.CertStore.from_store(
            path=_CA_DIR,
            basename="mitmproxy",
            key_size=2048,
        )
        log.info("mitmproxy generated CA in %s", _CA_DIR)

    # Extract public cert from the combined PEM for users to trust.
    # mitmproxy also writes mitmproxy-ca-cert.pem, but we copy to our
    # canonical name (ca-cert.pem) for a cleaner user-facing path.
    mitm_pub_cert = os.path.join(_CA_DIR, "mitmproxy-ca-cert.pem")
    if os.path.isfile(mitm_pub_cert) and not os.path.isfile(_CA_CERT_PATH):
        import shutil

        shutil.copy2(mitm_pub_cert, _CA_CERT_PATH)
        os.chmod(_CA_CERT_PATH, 0o644)  # Ensure readable by Node.js tools
        log.info("CA public cert copied to %s", _CA_CERT_PATH)
    elif os.path.isfile(ca_combined) and not os.path.isfile(_CA_CERT_PATH):
        # Fallback: extract cert from combined PEM
        _extract_cert_from_combined(ca_combined, _CA_CERT_PATH)

    if not os.path.isfile(_CA_CERT_PATH):
        raise RuntimeError("CA generation failed: %s not created" % _CA_CERT_PATH)

    return _CA_CERT_PATH


def get_node_env() -> dict[str, str]:
    """Return env vars for Node.js tools to trust the forward proxy CA.

    Returns dict with NODE_EXTRA_CA_CERTS pointing to the CA cert.
    Empty dict if CA cert doesn't exist.
    """
    cert_path = get_ca_cert_path()
    if os.path.isfile(cert_path):
        return {"NODE_EXTRA_CA_CERTS": cert_path}
    return {}


def is_ca_trusted() -> bool:
    """Check if the CA certificate is trusted at system level.

    macOS: Checks System keychain for the certificate.
    Linux: Checks /usr/local/share/ca-certificates/ for the cert.
    """
    system = platform.system()
    if system == "Darwin":
        return _is_trusted_macos()
    if system == "Linux":
        return _is_trusted_linux()
    return False


def install_ca_system() -> bool:
    """Install CA cert to the system trust store.

    Requires elevated privileges (sudo on macOS/Linux).

    macOS: Adds to System keychain as trusted root.
    Linux: Copies to /usr/local/share/ca-certificates/ and runs update-ca-certificates.

    Returns True on success, False on failure.
    """
    cert_path = get_ca_cert_path()
    if not os.path.isfile(cert_path):
        log.error("CA certificate not found: %s", cert_path)
        return False

    system = platform.system()
    if system == "Darwin":
        return _install_ca_macos(cert_path)
    if system == "Linux":
        return _install_ca_linux(cert_path)

    log.error("system CA install not supported on %s", system)
    return False


def print_setup_instructions() -> None:
    """Print instructions for configuring AI tools to use the forward proxy."""
    cert_path = get_ca_cert_path()
    trusted = is_ca_trusted()

    print("Forward Proxy CA Certificate")
    print("=" * 40)
    print("  Path:    %s" % cert_path)
    print("  Exists:  %s" % ("yes" if os.path.isfile(cert_path) else "no"))
    print("  Trusted: %s" % ("yes (system)" if trusted else "no"))
    print()

    if not trusted:
        print("To trust the CA system-wide (requires admin):")
        print("  sudo lumen-argus-agent forward-proxy install-ca")
        print()

    print("For Node.js tools (per-session, no admin needed):")
    print("  export NODE_EXTRA_CA_CERTS=%s" % cert_path)
    print()
    print("Tool-specific aliases (recommended):")
    print("  alias copilot='HTTPS_PROXY=http://localhost:9090 NODE_EXTRA_CA_CERTS=%s copilot'" % cert_path)


# ---------------------------------------------------------------------------
# CA cert extraction
# ---------------------------------------------------------------------------


def _extract_cert_from_combined(combined_path: str, cert_path: str) -> None:
    """Extract the public certificate from a combined key+cert PEM file."""
    with open(combined_path, "r") as f:
        content = f.read()

    # Find the certificate block
    begin = content.find("-----BEGIN CERTIFICATE-----")
    end = content.find("-----END CERTIFICATE-----")
    if begin == -1 or end == -1:
        log.error("no certificate found in %s", combined_path)
        return

    cert_pem = content[begin : end + len("-----END CERTIFICATE-----")] + "\n"
    fd = os.open(cert_path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o644)
    with os.fdopen(fd, "w") as f:
        f.write(cert_pem)
    log.info("extracted public cert to %s", cert_path)


# ---------------------------------------------------------------------------
# System trust store
# ---------------------------------------------------------------------------


def _is_trusted_macos() -> bool:
    """Check if CA is in macOS System keychain."""
    try:
        result = subprocess.run(
            ["security", "find-certificate", "-c", _CA_CN, "/Library/Keychains/System.keychain"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        return result.returncode == 0
    except (OSError, subprocess.TimeoutExpired):
        return False


def _is_trusted_linux() -> bool:
    """Check if CA is in Linux system trust store."""
    dest = "/usr/local/share/ca-certificates/lumen-argus-ca.crt"
    return os.path.isfile(dest)


def _install_ca_macos(cert_path: str) -> bool:
    """Install CA to macOS System keychain."""
    try:
        result = subprocess.run(
            [
                "security",
                "add-trusted-cert",
                "-d",  # add to admin cert store
                "-r",
                "trustRoot",  # trust as root CA
                "-k",
                "/Library/Keychains/System.keychain",
                cert_path,
            ],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode == 0:
            log.info("CA certificate installed to macOS System keychain")
            return True
        log.error("macOS CA install failed: %s", result.stderr.strip())
        return False
    except (OSError, subprocess.TimeoutExpired) as exc:
        log.error("macOS CA install failed: %s", exc, exc_info=True)
        return False


def _install_ca_linux(cert_path: str) -> bool:
    """Install CA to Linux system trust store."""
    dest = "/usr/local/share/ca-certificates/lumen-argus-ca.crt"
    try:
        # Copy cert
        import shutil

        shutil.copy2(cert_path, dest)

        # Update trust store
        result = subprocess.run(
            ["update-ca-certificates"],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode == 0:
            log.info("CA certificate installed to Linux trust store")
            return True
        log.error("update-ca-certificates failed: %s", result.stderr.strip())
        return False
    except (OSError, subprocess.TimeoutExpired) as exc:
        log.error("Linux CA install failed: %s", exc, exc_info=True)
        return False
